// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: ChargerStation

#ifndef _CHARGERSTATION_UI_H
#define _CHARGERSTATION_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_MainHeader;
extern lv_obj_t * ui_HeaderUSBC;
extern lv_obj_t * ui_HeaderUSBA;
void ui_event_USBCSwitch(lv_event_t * e);
extern lv_obj_t * ui_USBCSwitch;
void ui_event_USBASwitch(lv_event_t * e);
extern lv_obj_t * ui_USBASwitch;
void ui_event_Setting(lv_event_t * e);
extern lv_obj_t * ui_Setting;
extern lv_obj_t * ui_ImageSetting;
extern lv_obj_t * ui_InformationDock;
extern lv_obj_t * ui_Voltage;
extern lv_obj_t * ui_TextU;
extern lv_obj_t * ui_TextV;
extern lv_obj_t * ui_Current;
extern lv_obj_t * ui_TextI;
extern lv_obj_t * ui_TextA;
extern lv_obj_t * ui_Power;
extern lv_obj_t * ui_TextP;
extern lv_obj_t * ui_TextW;
extern lv_obj_t * ui_ImageWiFi;
extern lv_obj_t * ui_Hour;
extern lv_obj_t * ui_Minute;
extern lv_obj_t * ui_Second;
extern lv_obj_t * ui_TextHM;
extern lv_obj_t * ui_TextMS;
extern lv_obj_t * ui_USBADock;
extern lv_obj_t * ui_ImageUSBA;
extern lv_obj_t * ui_VoltageUSBA;
extern lv_obj_t * ui_USBC3Dock;
extern lv_obj_t * ui_ImageUSBC3;
extern lv_obj_t * ui_VoltageUSBC3;
extern lv_obj_t * ui_USBC2Dock;
extern lv_obj_t * ui_ImageUSBC2;
extern lv_obj_t * ui_ImageUSBC2Fast;
extern lv_obj_t * ui_VoltageUSBC2;
extern lv_obj_t * ui_USBC1Dock;
extern lv_obj_t * ui_ImageUSBC1;
extern lv_obj_t * ui_ImageUSBC1Fast;
extern lv_obj_t * ui_VoltageUSBC1;
// CUSTOM VARIABLES

// SCREEN: ui_SettingScreen
void ui_SettingScreen_screen_init(void);
extern lv_obj_t * ui_SettingScreen;
extern lv_obj_t * ui_SettingHeader;
extern lv_obj_t * ui_TextSettingHeader;
extern lv_obj_t * ui_FreeSpace;
extern lv_obj_t * ui_SettingDock;
extern lv_obj_t * ui_WiFiWebPage;
extern lv_obj_t * ui_ImageWiFiWebPage;
extern lv_obj_t * ui_TextWiFiWebPage;
void ui_event_ADCAdjust(lv_event_t * e);
extern lv_obj_t * ui_ADCAdjust;
extern lv_obj_t * ui_ImageADCAdjust;
extern lv_obj_t * ui_TextADCAdjust;
extern lv_obj_t * ui_PanelFanSwitch;
extern lv_obj_t * ui_ImageFanSwitch;
extern lv_obj_t * ui_TextFanSwitch;
void ui_event_FanSwitch(lv_event_t * e);
extern lv_obj_t * ui_FanSwitch;
void ui_event_SliderSleepTime(lv_event_t * e);
extern lv_obj_t * ui_SliderSleepTime;
extern lv_obj_t * ui_ImageSleepTime;
extern lv_obj_t * ui_SleepTime;
void ui_event_SliderBrightness(lv_event_t * e);
extern lv_obj_t * ui_SliderBrightness;
extern lv_obj_t * ui_ImageBrightness;
extern lv_obj_t * ui_Brightness;
void ui_event_Back(lv_event_t * e);
extern lv_obj_t * ui_Back;
extern lv_obj_t * ui_ImageBack;
extern lv_obj_t * ui_TextBack;
// CUSTOM VARIABLES

// SCREEN: ui_ADCAdjustScreen
void ui_ADCAdjustScreen_screen_init(void);
extern lv_obj_t * ui_ADCAdjustScreen;
extern lv_obj_t * ui_ADCHeader;
extern lv_obj_t * ui_TextADCHeader;
extern lv_obj_t * ui_ADCAdjustDock;
void ui_event_USBAAdjust(lv_event_t * e);
extern lv_obj_t * ui_USBAAdjust;
extern lv_obj_t * ui_ImageUSBAAdjust;
extern lv_obj_t * ui_VoltageUSBAADC;
void ui_event_USBC3Adjust(lv_event_t * e);
extern lv_obj_t * ui_USBC3Adjust;
extern lv_obj_t * ui_ImageUSBC3Adjust;
extern lv_obj_t * ui_VoltageUSBC3ADC;
void ui_event_USBC2Adjust(lv_event_t * e);
extern lv_obj_t * ui_USBC2Adjust;
extern lv_obj_t * ui_ImageUSBC2Adjust;
extern lv_obj_t * ui_ImageUSBC3AdjustB;
extern lv_obj_t * ui_VoltageUSBC2ADC;
void ui_event_USBC1Adjust(lv_event_t * e);
extern lv_obj_t * ui_USBC1Adjust;
extern lv_obj_t * ui_ImageUSBC1Adjust;
extern lv_obj_t * ui_ImageUSBC3AdjustB1;
extern lv_obj_t * ui_VoltageUSBC1ADC;
void ui_event_ADCBack(lv_event_t * e);
extern lv_obj_t * ui_ADCBack;
extern lv_obj_t * ui_ImageADCBack;
extern lv_obj_t * ui_TextADCBack;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_426970754);    // assets/mdi_usb-c-port.png
LV_IMG_DECLARE(ui_img_2092987087);    // assets/icon-park-outline_usb-micro-one.png
LV_IMG_DECLARE(ui_img_1671917170);    // assets/material-symbols_settings-rounded.png
LV_IMG_DECLARE(ui_img_1338783594);    // assets/material-symbols_wifi-off-rounded.png
LV_IMG_DECLARE(ui_img_175199537);    // assets/mynaui_lightning-solid.png
LV_IMG_DECLARE(ui_img_593743026);    // assets/material-symbols_wifi-rounded.png
LV_IMG_DECLARE(ui_img_155116563);    // assets/material-symbols_instant-mix-rounded.png
LV_IMG_DECLARE(ui_img_2103744591);    // assets/material-symbols_mode-fan-outline.png
LV_IMG_DECLARE(ui_img_123890670);    // assets/icon-park-outline_sleep.png
LV_IMG_DECLARE(ui_img_763584403);    // assets/iconamoon_mode-light.png
LV_IMG_DECLARE(ui_img_852573520);    // assets/material-symbols_chevron-left-rounded.png

// FONTS
LV_FONT_DECLARE(ui_font_ASCII20MONO);
LV_FONT_DECLARE(ui_font_ASCII32MONO);
LV_FONT_DECLARE(ui_font_ASCII40MONO);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
